# Generated by Django 4.2.7 on 2024-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('artisan', 'Artisan'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
