# Generated by Django 4.2.7 on 2024-05-29 19:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration',
            field=models.TextField(blank=True, unique=True, validators=[users.models.validate]),
        ),
    ]
