# Generated by Django 4.2.7 on 2024-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('artisan', 'Artisan'), ('client', 'Client')], max_length=20),
        ),
    ]
