# Generated by Django 4.2.7 on 2024-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('commercial', 'Commercial'), ('sejnen', 'Sejnen'), ('region', 'Region'), ('handicape', 'Handicapé'), ('nouveau artisan', 'Nouveau Artisan')], max_length=55)),
                ('description', models.TextField(max_length=512)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
