# Generated by Django 4.2.7 on 2024-06-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
