
# regions/governments list
REGIONS = [
    ('Ariana', 'Ariana'),
    ('Béja', 'Béja'),
    ('Ben Arous', 'Ben Arous'),
    ('Bizerte', 'Bizerte'),
    ('Gabés', 'Gabés'),
    ('Gafsa', 'Gafsa'),
    ('Jendouba', 'Jendouba'),
    ('Kairouan', 'Kairouan'),
    ('Kasserine', 'Kasserine'),
    ('Kébili', 'Kébili'),
    ('Le Kef', 'Le Kef'),
    ('Mahdia', 'Mahdia'),
    ('Manouba', 'Manouba'),
    ('Médenine', 'Médenine'),
    ('Monastir', 'Monastir'),
    ('Nabeul', 'Nabeul'),
    ('Sfax', 'Sfax'),
    ('Sidi Bouzid', 'Sidi Bouzid'),
    ('Siliana', 'Siliana'),
    ('Sousse', 'Sousse'),
    ('Tataouine', 'Tataouine'),
    ('Tozeur', 'Tozeur'),
    ('Tunis', 'Tunis'),
    ('Zaghouane', 'Zaghouane'),
]